const specialties = [
  { specialties: 'Allergy' },
  { specialties: 'Anesthesiology and Pain Management' },
  { specialties: 'Cardiology' },
  { specialties: 'Critical Care' },
  { specialties: 'Dermatology' },
  { specialties: 'Emergency Medicine' },
  { specialties: 'Endocrinology' },
  { specialties: 'Family Medicine' },
  { specialties: 'Gastroenterology' },
  { specialties: 'Geriatrics' },
  { specialties: 'Gynecology' },
  { specialties: 'Hematology' },
  { specialties: 'Hepatology' },
  { specialties: 'Hospital Medicine' },
  { specialties: 'Immunology' },
  { specialties: 'Infectious Diseases' },
  { specialties: 'Internal Medicine' },
  { specialties: 'Neonatology' },
  { specialties: 'Nephrology' },
  { specialties: 'Neurology' },
  { specialties: 'Neurosurgery' },
  { specialties: 'Obesity' },
  { specialties: 'Obstetric Medicine' },
  { specialties: 'Occupational Medicine' },
  { specialties: 'Oncology' },
  { specialties: 'Ophthalmology' },
  { specialties: 'Oral Health' },
  { specialties: 'Orthopedics and Sports Medicine' },
  { specialties: 'Otolaryngology' },
  { specialties: 'Palliative Care' },
  { specialties: 'Pathology and Laboratory Medicine' },
  { specialties: 'Pediatrics' },
  { specialties: 'Physical Medicine and Rehabilitation' },
  { specialties: 'Primary Care' },
  { specialties: 'Psychiatry' },
  { specialties: 'Pulmonary Medicine' },
  { specialties: 'Radiation Oncology' },
  { specialties: 'Radiology' },
  { specialties: 'Rheumatology' },
  { specialties: 'Sleep Medicine' },
  { specialties: 'Substance Use and Addiction Medicine' },
  { specialties: 'Surgery' },
  { specialties: 'Trauma' },
  { specialties: 'Urology' },
  { specialties: "Women's Health" },
];

export default specialties;
